---
- name: Converge
  hosts: privacyidea
  become: yes
  vars_files:
    - vars/selinux.yml
    - vars/firewall.yml
  roles: 
    - geerlingguy.apache 
    - role: ansible-role-privacyidea 
      vars:
        pi_db_hostname: 192.168.56.3
    - linux-system-roles.selinux
    - linux-system-roles.firewall
  tasks:
    - name: include apache.yml
      include_vars: vars/apache.yml
    - name: apply geerlingguy.apache again with vars because of chicken egg problem
      include_role:
        name: geerlingguy.apache
