---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 3"

defaults:
  run:
    working-directory: 'gitarplayer.privacyidea'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'gitarplayer.privacyidea'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code.
        run: |
          set -e
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - almalinux/8
#          - almalinux/9 python38 is not available yet and might never be 
#            maybe we could compile it from source or just wait?
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'gitarplayer.privacyidea'

      - name: Install pythons for to
        run:  sudo add-apt-repository ppa:deadsnakes/ppa -y && sudo apt-get update -y && sudo apt-get install -y python3.7 python3.7-distutils python3.8 python3.8-distutils python3.9 python3.9-distutils python3.10 python3.10-distutils

      - name: Install tox-ansible
        run: pip3 install tox-ansible tox

      - name: Run molecule tests against ansible 6.x and python >= 3.7
        run: tox
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          VAGRANT_BOX: ${{ matrix.distro }}
          TOX_TESTENV_PASSENV: VAGRANT_BOX 