---
name: Molecule Testing
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 3"

defaults:
  run:
    working-directory: 'gitarplayer.privacyidea'

jobs:

 molecule:
    name: Molecule
    runs-on: macos-10.15
    strategy:
      matrix:
        distro:
          - almalinux/8
#          - almalinux/9 python38 is not available yet and might never be 
#            maybe we could compile it from source or just wait?
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'gitarplayer.privacyidea'

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Install pythons for tox
        run:  brew install python@3.7 python@3.8 python@3.9 python@3.10

      - name: Install tox-ansible
        run: pip3 install tox-ansible

      - name: Run molecule tests against ansible 6.x and python >= 3.7
        run: tox
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          TOX_SKIP_ENV: '.*lint_all$'
          VAGRANT_BOX: ${{ matrix.distro }}
          TOX_TESTENV_PASSENV: VAGRANT_BOX TOX_SKIP_ENV